print("hello world")
print(5)
print(10 + 15)
print("This is day 1 of learning Python!")
print("I am excited to learn more about programming.")
print("krish is \"learning python\" \n he is doing great")
print("hello", 6, 6, sep="-")
print("hello", 6, 6, sep="-",end= "***\n")
print("krish")
print("This is the end of day 1.")